UnDo
3# Get editor completions based on the config schema
4"$schema" = 'https://starship.rs/config-schema.json'
,# Inserts a blank line between shell prompts
add_newline = true
3# Replace the '
' symbol in the prompt with '
F[character] # The name of the module we are configuring is 'character'
usuccess_symbol = '[
](bold green)' # The 'success_symbol' segment is being set to '
' with the color 'bold green'
B# Disable the package module, hiding it from the prompt completely
[package]
disabled = true5
