UnDo
+CPsy>Hm
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJYnRJVlJUYWhZY0l3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek00T0RNeE9Ua3lNQjRYRFR
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3SGhjTk1qVXdNakEyTURnMU16RXlXaGNOTXpVd01qQTBNRGcxTXpFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQ2hKUVBXQ2tKNEI1ZHBLeSs3cmpUVHJQSjhTVzVqbmUxZEtmL1Qwc2IKYlNqYU1NY3plczh3SmwxQzl6eWhTUGxxN2hKWDFxc1RzSjlnUUxIMzBwSE1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVydzJ6ZUJQbUY2NmQvWjNGT1NjCmZJOVo4dTB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1YdkcyZVloRHN2ZHRPQ1N0YXBHZllqUEpVaWQ5VHQKM3
        
- cluster:
@    certificate-authority: /Users/matthewholden/.minikube/ca.crt
    extensions:
    - extension:
2        last-update: Thu, 20 Feb 2025 12:50:49 CST
&        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    name: iiot
#    server: https://127.0.0.1:61172
  name: minikube
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3SGhjTk1qVXdNakEyTURnMU16RXlXaGNOTXpVd01qQTBNRGcxTXpFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQ2hKUVBXQ2tKNEI1ZHBLeSs3cmpUVHJQSjhTVzVqbmUxZEtmL1Qwc2IKYlNqYU1NY3plczh3SmwxQzl6eWhTUGxxN2hKWDFxc1RzSjlnUUxIMzBwSE1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVydzJ6ZUJQbUY2NmQvWjNGT1NjCmZJOVo4dTB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1YdkcyZVloRHN2ZHRPQ1N0YXBHZllqUEpVaWQ5VHQKM3BUaG1LUFllckJFQWlFQWtISU1BeFBqWDVDY1NOcjNSU3Y3MDRCendlY3hDaWU3WXkxZEFuQ1laT1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
"    server: https://127.0.0.1:6443
  name: rancher-desktop
- context:
    cluster: minikube
    extensions:
    - extension:
2        last-update: Thu, 20 Feb 2025 12:50:49 CST
&        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: rancher-desktop
    user: rancher-desktop
  name: rancher-desktop
- name: minikube
  user:
S    client-certificate: /Users/matthewholden/.minikube/profiles/minikube/client.crt
K    client-key: /Users/matthewholden/.minikube/profiles/minikube/client.key
- name: rancher-desktop
  user:
A    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJYnRJVlJUYWhZY0l3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek00T0RNeE9Ua3lNQjRYRFRJMU1ESXdOakE0TlRNeE1sb1hEVEkyTURJdwpOakE0TlRNeE1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFSCtzZzE3c0pkUWtlU3gKSWNCSUdESXVVMnJUeHVMVjVWMFhjak81R0VYM2ZWWG5UR1NIYThoMzB0VHJ1dk9CQVErZFMraEZEaS8xZlQyUQpqUVg1K2dtalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXMxOXQrdE45SHd5M1VrSWovTTFJYkNPSjdVVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQW1sbTZ6bFRzcFF3ZHdubU90cDRqOUp5K05QZEJhL2gvdHRvajNJbVFYeThDSVFEekorTy9hZ0pOUXUxVgppZmQ3eW5NWUpPQm1oS09mdjZkUmdDeUY0NUFVNnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM016ZzRNekU1T1RJd0hoY05NalV3TWpBMk1EZzFNekV5V2hjTk16VXdNakEwTURnMU16RXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM016ZzRNekU1T1RJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVG0wODVnMEU5R1RvZnNWTVhQZ3BzMkRJTzA3d0ZaRjVEYWlxRkd1ZWZlCmNDZkxZdmFMR2VOV0FrRERHTThMMkZKZlpqQkdjUFRHSUhSMWk3Zk9zSitabzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVMTmZiZnJUZlI4TXQxSkNJL3pOUwpHd2ppZTFFd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMdjF6anNEMktDVDBBQUVicnk1eFdOMi9lVXp3V1ljCnJpS3h6UW1xV1hVTUFpQWhwMlhBVVdFNkRlZnJ4aTJJblcycXhaN2FKNHJra3h2b3Bxa0NRc25Zb3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
E    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdtQkowYjF5cjZtRE5FR000SndnRE4ycXdDNGtleENyU2xSOFdWcHMwRytvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUWY2eURYdXdsMUNSNUxFaHdFZ1lNaTVUYXRQRzR0WGxYUmR5TTdrWVJmZDlWZWRNWklkcgp5SGZTMU91Njg0RUJENTFMNkVVT0wvVjlQWkNOQmZuNkNRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
apiVersion: v1
clusters:
  - cluster:
B      certificate-authority: /Users/matthewholden/.minikube/ca.crt
      extensions:
        - extension:
6            last-update: Thu, 20 Feb 2025 12:50:49 CST
*            provider: minikube.sigs.k8s.io
            version: v1.35.0
          name: cluster_info
      name: iiot
%      server: https://127.0.0.1:61172
    name: minikube
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3SGhjTk1qVXdNakEyTURnMU16RXlXaGNOTXpVd01qQTBNRGcxTXpFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpnNE16RTVPVEl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQ2hKUVBXQ2tKNEI1ZHBLeSs3cmpUVHJQSjhTVzVqbmUxZEtmL1Qwc2IKYlNqYU1NY3plczh3SmwxQzl6eWhTUGxxN2hKWDFxc1RzSjlnUUxIMzBwSE1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVydzJ6ZUJQbUY2NmQvWjNGT1NjCmZJOVo4dTB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1YdkcyZVloRHN2ZHRPQ1N0YXBHZllqUEpVaWQ5VHQKM3BUaG1LUFllckJFQWlFQWtISU1BeFBqWDVDY1NOcjNSU3Y3MDRCendlY3hDaWU3WXkxZEFuQ1laT1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
$      server: https://127.0.0.1:6443
    name: rancher-desktop
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
6            last-update: Thu, 20 Feb 2025 12:50:49 CST
*            provider: minikube.sigs.k8s.io
            version: v1.35.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
  - context:
      cluster: rancher-desktop
      user: rancher-desktop
    name: rancher-desktop
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
U      client-certificate: /Users/matthewholden/.minikube/profiles/minikube/client.crt
M      client-key: /Users/matthewholden/.minikube/profiles/minikube/client.key
  - name: rancher-desktop
    user:
C      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJYnRJVlJUYWhZY0l3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek00T0RNeE9Ua3lNQjRYRFRJMU1ESXdOakE0TlRNeE1sb1hEVEkyTURJdwpOakE0TlRNeE1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFSCtzZzE3c0pkUWtlU3gKSWNCSUdESXVVMnJUeHVMVjVWMFhjak81R0VYM2ZWWG5UR1NIYThoMzB0VHJ1dk9CQVErZFMraEZEaS8xZlQyUQpqUVg1K2dtalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXMxOXQrdE45SHd5M1VrSWovTTFJYkNPSjdVVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQW1sbTZ6bFRzcFF3ZHdubU90cDRqOUp5K05QZEJhL2gvdHRvajNJbVFYeThDSVFEekorTy9hZ0pOUXUxVgppZmQ3eW5NWUpPQm1oS09mdjZkUmdDeUY0NUFVNnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM016ZzRNekU1T1RJd0hoY05NalV3TWpBMk1EZzFNekV5V2hjTk16VXdNakEwTURnMU16RXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM016ZzRNekU1T1RJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBVG0wODVnMEU5R1RvZnNWTVhQZ3BzMkRJTzA3d0ZaRjVEYWlxRkd1ZWZlCmNDZkxZdmFMR2VOV0FrRERHTThMMkZKZlpqQkdjUFRHSUhSMWk3Zk9zSitabzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVMTmZiZnJUZlI4TXQxSkNJL3pOUwpHd2ppZTFFd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMdjF6anNEMktDVDBBQUVicnk1eFdOMi9lVXp3V1ljCnJpS3h6UW1xV1hVTUFpQWhwMlhBVVdFNkRlZnJ4aTJJblcycXhaN2FKNHJra3h2b3Bxa0NRc25Zb3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
G      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdtQkowYjF5cjZtRE5FR000SndnRE4ycXdDNGtleENyU2xSOFdWcHMwRytvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUWY2eURYdXdsMUNSNUxFaHdFZ1lNaTVUYXRQRzR0WGxYUmR5TTdrWVJmZDlWZWRNWklkcgp5SGZTMU91Njg0RUJENTFMNkVVT0wvVjlQWkNOQmZuNkNRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=5
